/**
 * Tests for the os-release generator.
 *
 * @module tests/os-release
 */

import { jest } from '@jest/globals';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import {
  parseOsRelease,
  formatOsRelease,
  generateOsRelease,
  readOsRelease,
  updateOsRelease,
} from '../src/generators/os-release.js';
import type { OsRelease } from '../src/generators/os-release.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function makeTempVault(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'agentfs-os-release-'));
  await fs.mkdir(path.join(dir, '.agentos'), { recursive: true });
  return dir;
}

// ---------------------------------------------------------------------------
// parseOsRelease / formatOsRelease round-trip
// ---------------------------------------------------------------------------

describe('parseOsRelease', () => {
  it('parses all four fields from a well-formed file', () => {
    const content = [
      '# Auto-generated by AgentFS — do not edit',
      'NAME="AgentFS"',
      'VERSION="1.2.3"',
      'SCHEMA_VERSION="1"',
      'VAULT_CREATED="2025-01-01"',
      '',
    ].join('\n');

    const result = parseOsRelease(content);
    expect(result.NAME).toBe('AgentFS');
    expect(result.VERSION).toBe('1.2.3');
    expect(result.SCHEMA_VERSION).toBe(1);
    expect(result.VAULT_CREATED).toBe('2025-01-01');
  });

  it('ignores blank lines and comment lines', () => {
    const content = '\n# comment\nNAME="AgentFS"\nVERSION="0.1.0"\nSCHEMA_VERSION="1"\nVAULT_CREATED="2024-06-01"\n';
    const result = parseOsRelease(content);
    expect(result.VERSION).toBe('0.1.0');
  });
});

describe('formatOsRelease → parseOsRelease round-trip', () => {
  it('serializes and re-parses without data loss', () => {
    const original: OsRelease = {
      NAME: 'AgentFS',
      VERSION: '0.5.0',
      SCHEMA_VERSION: 1,
      VAULT_CREATED: '2025-03-15',
    };

    const serialized = formatOsRelease(original);
    const parsed = parseOsRelease(serialized);

    expect(parsed).toEqual(original);
  });

  it('includes the auto-generated header comment', () => {
    const data: OsRelease = { NAME: 'AgentFS', VERSION: '1.0.0', SCHEMA_VERSION: 1, VAULT_CREATED: '2025-01-01' };
    const output = formatOsRelease(data);
    expect(output).toMatch(/^# Auto-generated by AgentFS/);
  });
});

// ---------------------------------------------------------------------------
// generateOsRelease — idempotency
// ---------------------------------------------------------------------------

describe('generateOsRelease', () => {
  it('creates .agentos/os-release on first call', async () => {
    const vault = await makeTempVault();
    const result = await generateOsRelease(vault, '0.1.0');

    expect(result.created).toContain('.agentos/os-release');
    expect(result.skipped).toHaveLength(0);

    const content = await fs.readFile(path.join(vault, '.agentos', 'os-release'), 'utf8');
    expect(content).toContain('VERSION="0.1.0"');
    expect(content).toContain('NAME="AgentFS"');
  });

  it('skips the file if it already exists (idempotent)', async () => {
    const vault = await makeTempVault();

    // First call — creates the file.
    await generateOsRelease(vault, '0.1.0');

    // Second call — must skip.
    const result = await generateOsRelease(vault, '0.2.0');
    expect(result.skipped).toContain('.agentos/os-release');
    expect(result.created).toHaveLength(0);

    // File content must still reflect the original version.
    const parsed = await readOsRelease(vault);
    expect(parsed?.VERSION).toBe('0.1.0');
  });
});

// ---------------------------------------------------------------------------
// readOsRelease
// ---------------------------------------------------------------------------

describe('readOsRelease', () => {
  it('returns null when the file does not exist', async () => {
    const vault = await makeTempVault();
    const result = await readOsRelease(vault);
    expect(result).toBeNull();
  });

  it('parses an existing file correctly', async () => {
    const vault = await makeTempVault();
    await generateOsRelease(vault, '1.0.0');

    const result = await readOsRelease(vault);
    expect(result).not.toBeNull();
    expect(result!.NAME).toBe('AgentFS');
    expect(result!.VERSION).toBe('1.0.0');
    expect(result!.SCHEMA_VERSION).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// updateOsRelease
// ---------------------------------------------------------------------------

describe('updateOsRelease', () => {
  it('updates VERSION but preserves VAULT_CREATED', async () => {
    const vault = await makeTempVault();

    // Seed an os-release with a known created date.
    await generateOsRelease(vault, '0.1.0');
    const original = await readOsRelease(vault);
    const originalCreated = original!.VAULT_CREATED;

    // Update to a newer version.
    const output = await updateOsRelease(vault, '0.9.0', false);

    expect(output.path).toBe('.agentos/os-release');
    expect(output.managed).toBe(true);
    expect(output.content).toContain('VERSION="0.9.0"');
    expect(output.content).toContain(`VAULT_CREATED="${originalCreated}"`);
  });

  it('creates a fresh record when os-release does not exist', async () => {
    const vault = await makeTempVault();
    const output = await updateOsRelease(vault, '0.5.0', false);

    expect(output.content).toContain('VERSION="0.5.0"');
    expect(output.content).toContain('NAME="AgentFS"');
    expect(output.content).toContain('SCHEMA_VERSION="1"');
  });

  it('returns a CompileOutput with managed=true', async () => {
    const vault = await makeTempVault();
    const output = await updateOsRelease(vault, '1.0.0', true);
    expect(output.managed).toBe(true);
  });
});
