/**
 * Manifest Generator — creates `.agentos/manifest.yaml`.
 *
 * Builds the kernel-space manifest from interactive setup answers and
 * writes it to `{targetDir}/.agentos/manifest.yaml`. Idempotent: skips
 * the file if it already exists.
 *
 * @see docs/architecture.md Section 2 "Kernel Space"
 * @module generators/manifest
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import type { Manifest, SetupAnswers, GeneratorResult } from '../types/index.js';
import { getDefaultPaths } from '../utils/fhs-mapping.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Current manifest schema version. */
const AGENTOS_VERSION = '1.0.0';

/**
 * Standard boot sequence — ordered list of init.d scripts loaded at startup.
 * Mirrors a minimal SysVinit runlevel 3 boot (see architecture §4).
 */
const BOOT_SEQUENCE: string[] = [
  '.agentos/init.d/00-identity.md',
  '.agentos/init.d/10-memory.md',
  '.agentos/init.d/20-today.md',
  '.agentos/init.d/30-projects.md',
];

/** Frontmatter fields every vault file must declare. */
const FRONTMATTER_REQUIRED: string[] = ['date', 'tags'];

/** Recommended but optional frontmatter fields. */
const FRONTMATTER_STANDARD: string[] = ['status', 'stream', 'origin'];

// ---------------------------------------------------------------------------
// buildManifest
// ---------------------------------------------------------------------------

/**
 * Constructs a typed `Manifest` object from setup answers.
 *
 * No I/O — pure transformation. The caller is responsible for serialising
 * and persisting the result.
 *
 * @param answers - Wizard answers collected during `npx create-agentfs`.
 * @returns A fully-populated `Manifest` ready for YAML serialisation.
 */
function buildManifest(answers: SetupAnswers): Manifest {
  return {
    agentos: {
      version: AGENTOS_VERSION,
      profile: answers.profile,
    },
    vault: {
      name: answers.vaultName,
      owner: answers.ownerName,
      created: new Date().toISOString().slice(0, 10), // YYYY-MM-DD
    },
    agents: {
      primary: answers.primaryAgent,
      supported: answers.supportedAgents,
    },
    paths: getDefaultPaths(answers.profile),
    boot: {
      sequence: BOOT_SEQUENCE,
    },
    frontmatter: {
      required: FRONTMATTER_REQUIRED,
      standard: FRONTMATTER_STANDARD,
    },
    ...(answers.modules.length > 0 ? { modules: answers.modules } : {}),
  };
}

// ---------------------------------------------------------------------------
// generateManifest
// ---------------------------------------------------------------------------

/**
 * Generates `.agentos/manifest.yaml` inside the target vault directory.
 *
 * Behaviour:
 * - Creates `.agentos/` directory if absent (recursive, safe).
 * - Skips writing if `manifest.yaml` already exists (idempotent).
 * - Serialises the manifest with `js-yaml` using 2-space indentation.
 *
 * @param answers - Setup answers from the interactive wizard.
 * @returns A `GeneratorResult` listing created and skipped paths.
 *
 * @example
 * ```ts
 * const result = await generateManifest(answers);
 * console.log(result.created);  // ['.agentos/manifest.yaml']
 * console.log(result.skipped);  // []
 * ```
 */
export async function generateManifest(answers: SetupAnswers): Promise<GeneratorResult> {
  const result: GeneratorResult = { created: [], skipped: [] };

  const agentosDir = path.join(answers.targetDir, '.agentos');
  const manifestPath = path.join(agentosDir, 'manifest.yaml');
  const manifestRelative = path.join('.agentos', 'manifest.yaml');

  // Ensure .agentos/ directory exists before checking the manifest.
  await fs.mkdir(agentosDir, { recursive: true });

  // Idempotency check — never overwrite an existing manifest.
  try {
    await fs.access(manifestPath);
    // File exists — skip.
    result.skipped.push(manifestRelative);
    return result;
  } catch {
    // File does not exist — proceed with creation.
  }

  const manifest = buildManifest(answers);

  const yamlContent =
    '# AgentFS manifest — generated by create-agentfs. Do not edit manually.\n' +
    '# See docs/architecture.md §2 for the full schema reference.\n\n' +
    yaml.dump(manifest, {
      indent: 2,
      lineWidth: 100,
      quotingType: "'",
      forceQuotes: false,
    });

  await fs.writeFile(manifestPath, yamlContent, 'utf8');
  result.created.push(manifestRelative);

  return result;
}
