/**
 * OS-release generator — creates and manages `.agentos/os-release`.
 *
 * Provides filesystem versioning for AgentFS vaults, modelled after the
 * standard Linux `/etc/os-release` format (KEY="value" pairs).
 *
 * @module generators/os-release
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import type { GeneratorResult, CompileOutput } from '../types/index.js';
import { CLI_VERSION } from '../utils/version.js';

/** Relative path of the os-release file within the vault. */
const OS_RELEASE_PATH = '.agentos/os-release';

// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

/** Fields stored in `.agentos/os-release`. */
export interface OsRelease {
  /** Always "AgentFS" */
  NAME: string;
  /** CLI version at the time of the last scaffold or compile */
  VERSION: string;
  /** Schema version — starts at 1, incremented on breaking format changes */
  SCHEMA_VERSION: number;
  /** ISO date when the vault was first created */
  VAULT_CREATED: string;
  /** ISO date of the last successful `agentfs upgrade` run (optional) */
  LAST_UPGRADE?: string;
}

// ---------------------------------------------------------------------------
// Parse / format
// ---------------------------------------------------------------------------

/**
 * Parse a KEY="value" os-release file into an OsRelease object.
 *
 * Lines that are blank or start with `#` are ignored.
 * Quoted values have their surrounding double-quotes stripped.
 *
 * @param content - Raw file content
 * @returns Parsed OsRelease object
 */
export function parseOsRelease(content: string): OsRelease {
  const result: Record<string, string> = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();

    // Strip surrounding double-quotes if present.
    if (value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  const schemaRaw = parseInt(result['SCHEMA_VERSION'] ?? '1', 10);
  if (isNaN(schemaRaw)) {
    throw new Error(`Corrupt os-release: SCHEMA_VERSION is not a valid number ("${result['SCHEMA_VERSION']}")`);
  }

  const parsed: OsRelease = {
    NAME: result['NAME'] ?? 'AgentFS',
    VERSION: result['VERSION'] ?? 'unknown',
    SCHEMA_VERSION: schemaRaw,
    VAULT_CREATED: result['VAULT_CREATED'] ?? 'unknown',
  };

  if (result['LAST_UPGRADE'] !== undefined) {
    parsed.LAST_UPGRADE = result['LAST_UPGRADE'];
  }

  return parsed;
}

/**
 * Serialize an OsRelease object to the KEY="value" file format.
 *
 * Includes a header comment warning against manual edits.
 *
 * @param data - OsRelease object to serialize
 * @returns File content string
 */
export function formatOsRelease(data: OsRelease): string {
  const lines = [
    '# Auto-generated by AgentFS — do not edit',
    `NAME="${data.NAME}"`,
    `VERSION="${data.VERSION}"`,
    `SCHEMA_VERSION="${data.SCHEMA_VERSION}"`,
    `VAULT_CREATED="${data.VAULT_CREATED}"`,
  ];

  if (data.LAST_UPGRADE !== undefined) {
    lines.push(`LAST_UPGRADE="${data.LAST_UPGRADE}"`);
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Scaffold integration
// ---------------------------------------------------------------------------

/**
 * Generate `.agentos/os-release` during vault scaffold.
 *
 * Idempotent: if the file already exists it is skipped.
 *
 * @param vaultRoot - Root directory of the vault
 * @param version - CLI version to record (defaults to package.json version)
 * @returns GeneratorResult listing created/skipped paths
 */
export async function generateOsRelease(
  vaultRoot: string,
  version: string = CLI_VERSION,
): Promise<GeneratorResult> {
  const result: GeneratorResult = { created: [], skipped: [] };
  const absPath = path.join(vaultRoot, OS_RELEASE_PATH);

  try {
    await fs.access(absPath);
    // File already exists — skip (idempotent).
    result.skipped.push(OS_RELEASE_PATH);
    return result;
  } catch {
    // File does not exist — write it.
  }

  const data: OsRelease = {
    NAME: 'AgentFS',
    VERSION: version,
    SCHEMA_VERSION: 1,
    VAULT_CREATED: new Date().toISOString().split('T')[0],
  };

  await fs.writeFile(absPath, formatOsRelease(data), 'utf8');
  result.created.push(OS_RELEASE_PATH);

  return result;
}

// ---------------------------------------------------------------------------
// Read helper
// ---------------------------------------------------------------------------

/**
 * Read and parse `.agentos/os-release`.
 *
 * @param vaultRoot - Root directory of the vault
 * @returns Parsed OsRelease or null if the file does not exist
 */
export async function readOsRelease(vaultRoot: string): Promise<OsRelease | null> {
  try {
    const content = await fs.readFile(path.join(vaultRoot, OS_RELEASE_PATH), 'utf8');
    return parseOsRelease(content);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Compile integration
// ---------------------------------------------------------------------------

/**
 * Read the existing os-release, update the VERSION field to the current CLI
 * version, and return a CompileOutput for use with writeOutputs().
 *
 * If the file does not exist, a fresh one is created in memory (not on disk —
 * writeOutputs handles the actual write).
 *
 * @param vaultRoot - Root directory of the vault
 * @param version - Current CLI version
 * @param dryRun - When true, nothing is written to disk
 * @returns CompileOutput ready for writeOutputs()
 */
export async function updateOsRelease(
  vaultRoot: string,
  version: string,
  _dryRun: boolean,
): Promise<CompileOutput> {
  const existing = await readOsRelease(vaultRoot);

  const data: OsRelease = existing
    ? { ...existing, VERSION: version }
    : {
        NAME: 'AgentFS',
        VERSION: version,
        SCHEMA_VERSION: 1,
        VAULT_CREATED: new Date().toISOString().split('T')[0],
      };

  return {
    path: OS_RELEASE_PATH,
    content: formatOsRelease(data),
    managed: true,
  };
}
