/**
 * Cursor compiler driver — Story 10.2.
 *
 * Compiles the AgentFS kernel into Cursor-native formats:
 * - .cursor/rules/agentfs-global.mdc: Modern Cursor rules with YAML frontmatter
 *
 * @module compilers/cursor
 */

import type { AgentCompiler, CompileContext, CompileResult } from '../types/index.js';

export const cursorCompiler: AgentCompiler = {
  name: 'cursor',

  async compile(context: CompileContext): Promise<CompileResult> {
    const { manifest, initScripts, corrections } = context;

    const lines: string[] = [];
    lines.push('---');
    lines.push('description: Global rules and project context for AgentFS Vault');
    lines.push('globs: ["**/*"]');
    lines.push('alwaysApply: true');
    lines.push('---');
    lines.push('');
    lines.push('# Cursor Rules — Generated by AgentFS');
    lines.push('');
    lines.push(`## Vault: ${manifest.vault?.name ?? 'AgentFS Vault'}`);
    lines.push(`## Profile: ${manifest.agentos?.profile ?? 'personal'}`);
    lines.push('');

    if (initScripts['00-identity.md']) {
      lines.push('### Identity');
      lines.push(initScripts['00-identity.md']);
      lines.push('');
    }

    if (manifest.paths) {
      lines.push('### Directory Structure');
      for (const [key, val] of Object.entries(manifest.paths)) {
        if (val) lines.push(`- ${key}: ${val}/`);
      }
      lines.push('');
    }

    if (manifest.boot?.sequence) {
      lines.push('### Boot Sequence');
      for (const script of manifest.boot.sequence) {
        lines.push(`- ${script}`);
      }
      lines.push('');
    }

    if (corrections) {
      lines.push('### Avoid These Mistakes');
      lines.push(corrections);
      lines.push('');
    }

    const content = lines.join('\n');

    return {
      agent: 'cursor',
      outputs: [
        { path: '.cursor/rules/agentfs-global.mdc', content, managed: true },
      ],
      summary: `Compiled .cursor/rules/agentfs-global.mdc for Cursor (vault: "${manifest.vault?.name ?? 'unknown'}")`,
    };
  },

  supports(_feature: string): boolean {
    // Cursor doesn't support native security enforcement in the formats we're compiling
    return false;
  },
};
